apiVersion: apps/v1

kind: Deployment

metadata:

  name: spring-boot-k8s-deployment

  labels:

    app: spring-boot-k8s

spec:

  replicas: 2

  selector:

    matchLabels:

      app: spring-boot-k8s

  template:

    metadata:

      labels:

        app: spring-boot-k8s

    spec:

      containers:

        - name: spring-boot-k8s

          image: my-spring-boot-app

          ports:

            - containerPort: 9000

---

apiVersion: v1
kind: Service
metadata:
  name: spring-boot-k8svc
spec:
  selector:
    app.kubernetes.io/name: spring-boot-k8s
  ports:
    - protocol: TCP
      port:9000
      targetPort: 9376
  type: NodePort
